/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\park.glb 
Author: LoneDeveloper (https://sketchfab.com/LoneDeveloper)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/epcot-futureworld-disney-world-theme-park-vr-39025bfd4c6e48daaa3c3544473870b4
Title: Epcot Futureworld - Disney World Theme Park - VR
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Model(props) {
  const { nodes, materials } = useGLTF("/park.glb");
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <group rotation={[-Math.PI / 2, 0, 0]} scale={4.094}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[2.569, 0.813, 12.437]}
              rotation={[0, -0.662, 0]}
              scale={[0.089, 0.624, 0.77]}
            >
              <mesh
                geometry={nodes.pCube29_blue1_0.geometry}
                material={materials.blue1}
              />
              <mesh
                geometry={nodes.pCube29_blue_0.geometry}
                material={materials.blue}
              />
            </group>
            <group
              position={[-2.544, 0.813, 12.461]}
              rotation={[0, 0.662, 0]}
              scale={[0.089, 0.624, 0.77]}
            >
              <mesh
                geometry={nodes.pCube30_blue1_0.geometry}
                material={materials.blue1}
              />
              <mesh
                geometry={nodes.pCube30_blue_0.geometry}
                material={materials.blue}
              />
            </group>
            <group
              position={[0.172, 4.971, -0.3]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={3.9}
            >
              <mesh
                geometry={nodes.polySurface133_planters_0.geometry}
                material={materials.planters}
                position={[0.124, 0.148, 0.175]}
                scale={[0.926, 1.127, 0.926]}
              />
              <mesh
                geometry={nodes.polySurface135_planters_0.geometry}
                material={materials.planters}
                position={[0.059, 0.145, -0.09]}
                scale={[0.926, 1.127, 0.926]}
              />
              <mesh
                geometry={nodes.polySurface136_planters_0.geometry}
                material={materials.planters}
                position={[0.121, 0.146, -0.156]}
                scale={[0.926, 1.127, 0.926]}
              />
            </group>
            <mesh
              geometry={
                nodes.polySurface42_spaceship_earth_buildings_0.geometry
              }
              material={materials.spaceship_earth_buildings}
            />
            <mesh
              geometry={nodes.pPlane1_ground_0.geometry}
              material={materials.ground}
              position={[0, 0.033, 0.337]}
              scale={87.932}
            />
            <mesh
              geometry={nodes.entrance_fountain_fountain1_0.geometry}
              material={materials.fountain1}
              position={[0, 0.009, -5.793]}
              scale={[1.161, 0.053, 1.161]}
            />
            <mesh
              geometry={nodes.polySurface125_planters_0.geometry}
              material={materials.planters}
              position={[0.501, 0.03, 0.771]}
              scale={[1.078, 1, 1.078]}
            />
            <mesh
              geometry={nodes.polySurface126_planters_0.geometry}
              material={materials.planters}
              position={[-0.505, 0.03, 0.771]}
              scale={[1.078, 1, 1.078]}
            />
            <mesh
              geometry={nodes.polySurface130_planters_0.geometry}
              material={materials.planters}
              position={[-0.253, 0.028, -0.425]}
              scale={0.93}
            />
            <mesh
              geometry={nodes.polySurface131_planters_0.geometry}
              material={materials.planters}
              position={[0.256, 0.028, -0.425]}
              scale={0.93}
            />
            <mesh
              geometry={nodes.pCylinder6_spaceship_earth_0.geometry}
              material={materials.spaceship_earth}
            />
            <mesh
              geometry={nodes.entranceBuildings_entrance_buildings_0.geometry}
              material={materials.entrance_buildings}
              position={[0, 0.005, 0]}
              scale={[1, 1.254, 1]}
            />
            <mesh
              geometry={nodes.monoliths_monolith_0.geometry}
              material={materials.monolith}
              position={[0.298, 4.072, -0.252]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={3.881}
            />
            <mesh
              geometry={nodes.innoventions_buildings_innoventions_0.geometry}
              material={materials.innoventions}
            />
            <mesh
              geometry={nodes.fountain_view_fountainView_0.geometry}
              material={materials.fountainView}
              position={[0.46, 0, -3.6]}
              scale={[1.143, 1, 1.143]}
            />
            <mesh
              geometry={nodes.center_piece_centerpiece_0.geometry}
              material={materials.centerpiece}
            />
            <mesh
              geometry={
                nodes.electric_umbrella_entrance_electric_umbrella37_0.geometry
              }
              material={materials.electric_umbrella37}
            />
            <mesh
              geometry={nodes.mousegear1_mouseGear_0.geometry}
              material={materials.mouseGear}
            />
            <mesh
              geometry={nodes.generic_planters_planters_0.geometry}
              material={materials.planters}
            />
            <mesh
              geometry={nodes.fountain_mid_fountain_0.geometry}
              material={materials.mid_fountain}
            />
          </group>
        </group>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/park.glb");
